name: Test systems

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: cachix use "altf4llc-os"
      - run: nix develop -c just cache-build 'build-darwin "x86_64"'

  nixos-desktop:
    strategy:
      matrix:
        desktop:
          - gnome
          - plasma5
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: cachix use "altf4llc-os"
      - run: nix develop -c just cache-build 'build-nixos-desktop "x86_64" "${{ matrix.desktop }}"'

  nixos-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: cachix use "altf4llc-os"
      - run: nix develop -c just cache-build 'build-nixos-minimal "x86_64"'
