name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: ${{ env.CACHIX_BINARY_CACHE }}
    - uses: actions/checkout@v4
    - run: nix develop -c just check
