name: Test languages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - bash
          - cpp-cmake
          - dart
          - go-mod
          - go-pkg
          - haskell
          - lua-app
          - nodejs-backend
          - ocaml
          - powershell
          - python-app
          - python-pkg
          - rust
          - zig
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: altf4llc-os
      - uses: actions/checkout@v3
      - run: cachix use "altf4llc-os"
      - run: nix develop -c just cache-build 'build-language "${{ matrix.template }}" "default"'

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - bash
          - cpp-cmake
          - dart
          - go-mod
          - go-pkg
          - haskell
          - nodejs-backend
          - ocaml
          - powershell
          - python-app
          - rust
          - zig
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: nix develop -c just cache-build 'build-language "${{ matrix.template }}" "docker"'
