name: Test systems

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: mkdir -p "${{ runner.temp }}/build"
      - run: nix develop -c just build-darwin "x86_64" "${{ runner.temp }}/build"

  nixos-desktop:
    strategy:
      matrix:
        desktop:
          - gnome
          - plasma5
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: mkdir -p "${{ runner.temp }}/build"
      - run: nix develop -c just build-nixos-desktop "x86_64" "${{ matrix.desktop }}" "${{ runner.temp }}/build"

  nixos-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: mkdir -p "${{ runner.temp }}/build"
      - run: nix develop -c just build-nixos-minimal "x86_64" "${{ runner.temp }}/build"
