on:
  pull_request:
  push:
    branches:
      - main

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-darwin "x86_64"

  nixos-desktop:
    strategy:
      matrix:
        desktop:
          - gnome
          - plasma5
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-nixos-desktop "x86_64" ${{ matrix.desktop }}

  nixos-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: just build-nixos-minimal "x86_64"
