name: Test home-manager

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: mkdir -p "${{ runner.temp }}/build"
      - run: nix develop -c just build-home-manager "x86_64-darwin" "${{ runner.temp }}/build"

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: mkdir -p "${{ runner.temp }}/build"
      - run: nix develop -c just build-home-manager "x86_64-linux" "${{ runner.temp }}/build"
