name: Test flake

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v12
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: altf4llc-os
    - uses: actions/checkout@v3
    - run: cachix use "altf4llc-os"
    - run: nix develop -c just check
    - run: nix develop -c just cache-inputs
    - run: nix develop -c just cache-shell
