name: 'Test NixOS Template(s)'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-desktop:
    strategy:
      matrix:
        desktop:
          - gnome
          - plasma5
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v3
      - run: bash hack/test-nixos.sh nixos-desktop ${{ matrix.desktop }}

  build-minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v3
      - run: bash hack/test-nixos.sh nixos-minimal
