---
name: 'Test Darwin Flake Template'

on:
  push:
    # branches: [main]
  pull_request:

jobs:
  build-nixos-deriv:
    name: 'Build Darwin template derivation'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: bash hack/test-darwin.sh
